CREATE TABLE [dbo].[View]
(
	[ID] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_View_ID] DEFAULT NEWID(),
	[Name] NVARCHAR(450) NOT NULL,
	[Document] XML NOT NULL,
	CONSTRAINT [PK_View_ID] PRIMARY KEY (ID),
	CONSTRAINT [UNQ_View_ID] UNIQUE (ID),
	CONSTRAINT [UNQ_View_Name] UNIQUE (Name)



)
